# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# 1. Maven Build
- task: Maven@4
  displayName: 'Build Java Application'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

# 2. Copy JAR to staging directory
- task: CopyFiles@2
  displayName: 'Copy JAR File'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# 3. Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'simple-app'
    publishLocation: 'Container'

# Docker Build and Push to ACR
- task: Docker@2
  displayName: 'Build and Push Docker Image to ACR'
  inputs:
    containerRegistry: 'suresh-acr-service'
    repository: 'simple-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
